name: miccai23_res
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.11.*
  - pip:
      - accelerate==0.25.0
      - antlr4-python3-runtime==4.9.3
      - appdirs==1.4.4
      - austin-dist==3.6.0
      - beautifulsoup4==4.12.2
      - bleach==6.1.0
      - certifi==2023.11.17
      - charset-normalizer==3.3.2
      - click==8.1.7
      - contourpy==1.2.0
      - cycler==0.12.1
      - diffusers==0.24.0
      - dipy==1.7.0
      - docker-pycreds==0.4.0
      - einops==0.7.0
      - filelock==3.13.1
      - fonttools==4.46.0
      - freia==0.2
      - fsspec==2023.12.1
      - gdown==4.7.1
      - gitdb==4.0.11
      - gitpython==3.1.40
      - h5py==3.10.0
      - huggingface-hub==0.19.4
      - idna==3.6
      - imageio==2.33.0
      - importlib-metadata==7.0.0
      - ipywidgets==8.1.1
      - jinja2==3.1.2
      - joblib==1.3.2
      - jupyterlab-widgets==3.0.9
      - kaggle==1.5.16
      - kiwisolver==1.4.5
      - lazy-loader==0.3
      - markupsafe==2.1.3
      - matplotlib==3.8.2
      - mpmath==1.3.0
      - networkx==3.2.1
      - nibabel==5.1.0
      - numpy==1.24.2
      - nvidia-cublas-cu12==12.1.3.1
      - nvidia-cuda-cupti-cu12==12.1.105
      - nvidia-cuda-nvrtc-cu12==12.1.105
      - nvidia-cuda-runtime-cu12==12.1.105
      - nvidia-cudnn-cu12==8.9.2.26
      - nvidia-cufft-cu12==11.0.2.54
      - nvidia-curand-cu12==10.3.2.106
      - nvidia-cusolver-cu12==11.4.5.107
      - nvidia-cusparse-cu12==12.1.0.106
      - nvidia-nccl-cu12==2.18.1
      - nvidia-nvjitlink-cu12==12.3.101
      - nvidia-nvtx-cu12==12.1.105
      - omegaconf==2.3.0
      - pie-torch==0.0.1
      - pillow==10.1.0
      - protobuf==4.25.1
      - psutil==5.9.6
      - pycocotools==2.0.7
      - pyparsing==3.1.1
      - pysocks==1.7.1
      - python-slugify==8.0.1
      - pyyaml==6.0.1
      - regex==2023.10.3
      - requests==2.31.0
      - safetensors==0.4.1
      - scikit-image==0.22.0
      - scikit-learn==1.3.2
      - scipy==1.11.4
      - sentry-sdk==1.38.0
      - setproctitle==1.3.3
      - setuptools==65.6.3
      - simpleitk==2.3.1
      - smmap==5.0.1
      - snakeviz==2.2.0
      - soupsieve==2.5
      - sympy==1.12
      - text-unidecode==1.3
      - threadpoolctl==3.2.0
      - tifffile==2023.9.26
      - tokenizers==0.15.0
      - torch==2.1.1
      - torchgeometry==0.1.2
      - torchinfo==1.8.0
      - torchvision==0.16.1
      - tqdm==4.65.0
      - transformers==4.36.0
      - triton==2.1.0
      - typing-extensions==4.8.0
      - urllib3==2.1.0
      - wandb==0.16.1
      - webencodings==0.5.1
      - widgetsnbextension==4.0.9
      - xformers==0.0.23